cursos-tutoriais/Tutorial_Django/tutorial/polls/urls.py
# from django.urls import path

# from . import views



# # é possivel nomear apps desta forma.
# # nao é preciso, mas no caso de da necessidade os links de html's devem mudar disto:

# # <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>

# # para isto:

# # <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

# app_name = 'polls'
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),

#     # ex: /polls/5/
#     path("<int:question_id>/", views.detail, name="detail"), 
#     # path("specifics/<int:question_id>/", views.detail, name="detail"),

#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),

#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

cursos-tutoriais/Tutorial_Django/tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

cursos-tutoriais/Tutorial_Django/tutorial/polls/models.py
from django.db import models
from django.utils import timezone 
import datetime
from django.contrib import admin
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
            
    @admin.display(
    boolean=True,
    ordering="pub_date",
    description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

cursos-tutoriais/Tutorial_Django/tutorial/polls/views.py
# from django.shortcuts import render

# # Create your views here.

# # modificação em reação ao tutorial  pondo F's strings

# from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
# # from django.http import Http404


# from django.shortcuts import get_object_or_404, redirect
# # Existe também a função get_list_or_404(), que trabalha da mesma forma que get_object_or_404()
# # – com a diferença de que ela usa filter() ao invés de get().
# # Ela levanta Http404 se a lista estiver vazia.


# from .models import Question, Choice
# from django.urls import reverse


# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "polls/index.html", context)
    



# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/detail.html", {"question": question})

# # def detail(request, question_id):
# #     try:
# #         question = Question.objects.get(pk=question_id)
# #     except Question.DoesNotExist:
# #         raise Http404("Question does not exist")
# #     return render(request, "polls/detail.html", {"question": question})




# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})




# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST["choice"])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, "polls/detail.html",
#             {
#                 "question": question,
#                 "error_message": "escolha uma cacete.",
#             },
#         )
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    
#     #  atentar para condição de concorrencia- ocorre quando dois usuarios enviam um formulario 
#     # ao mesmo tempo recebendo entao o mesmo valor :
    
#     # https://docs.djangoproject.com/pt-br/4.2/ref/models/expressions/#avoiding-race-conditions-using-f


from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    ...

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    ...  # same as above, no changes needed.
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, "polls/detail.html",
            {
                "question": question,
                "error_message": "escolha uma cacete.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

cursos-tutoriais/Tutorial_Django/tutorial/polls/templates/polls/detail.html
 {% comment %} <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>   {% endcomment %}

 <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            
    </fieldset>
    <input type="submit" value="Vote">
</form>

cursos-tutoriais/Tutorial_Django/tutorial/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<form class='q'>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}/" >{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</form>


{% comment %} 

Lembre-se, quando escrevemos o link para uma pergunta no template 
polls/templates/index.html, o link foi parcialmente codificado como este:

<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>

O problema com com essa abordagem acoplada, hardcoded é que torna muito difícil alterar URLs 
em projetos com muitos templates. Todavia, se definimos o argumento name nas funções path() 
no módulo polls.urls, você pode remover a dependência de um caminho de URL específico
 nas configurações de url usando a template tag

{% url %}:<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li> 
  
  {% endcomment %}

cursos-tutoriais/Tutorial_Django/tutorial/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>